# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven # Как называется workflow

on:  # Когда срабатывает (на push in main и pull_request)
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: # Какие задачи делаем
  build: # Сборка

    runs-on: ubuntu-latest # Где запускаем: ubuntu последней версии

    steps: # Шаги
    - uses: actions/checkout@v4 # Выкачиваем репозиторий
    - name: Set up JDK 25
      uses: actions/setup-java@v4 # Установка JDK
      with:
        java-version: '25' # Версия Java
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml # Запуск maven
    - name: Upload JaCoCo coverage report # Загрузка отчёта
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/
        retention-days: 30

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
